### ISSUE TITLE
Not getting imageUrl in some cases

### ISSUE THREAD

**Issue by RakeshImpinge** [marty-suzuki/URLEmbeddedView#16]
Thanks for this great library.
I am facing a problem in getting "imageUrl" for some case.

http://www.runnersworld.com/race-training/how-to-taper-for-your-first-half-marathon?utm_source=facebook.com&utm_medium=Social&utm_term=580876710&utm_campaign=Runner%E2%80%99s%20World

I am using OGDataProvider to extract the data.
[[OGDataProvider sharedInstance] fetchOGDataWithUrlString:url completion:^(OGData  data, NSError  error)

Any help is much appreciated.

**Comment by marty-suzuki** [comment]
Thank you for a issue.

Please see the html of [http://www.runnersworld.com/race-training/how-to-taper-for-your-first-half-marathon?utm_source=facebook.com&utm_medium=Social&utm_term=580876710&utm_campaign=Runner%E2%80%99s%20World](http://www.runnersworld.com/race-training/how-to-taper-for-your-first-half-marathon?utm_source=facebook.com&utm_medium=Social&utm_term=580876710&utm_campaign=Runner%E2%80%99s%20World)

This html doesn't have`<meta property="og:image" content="http://~" />`
Therefore can't get image.

**Comment by RakeshImpinge** [comment]
Thanks for prompt reply.
If you paste the same URL in Skype or Facebook they are displaying the Image.
Is this something this library does not support?

**Comment by marty-suzuki** [comment]
I think they search image from html when can't find `og:image`. In addition, I think they gather OGP data with server.
If `og:image` doesn't be contained in html, it is difficult to get matched image for web site.
That image might be AD image, header image and so on.

**Comment by RakeshImpinge** [comment]
I see. Thanks for the description.

**Comment by marty-suzuki** [comment]
Sorry that I can't live up to your expectations.

**Comment by RakeshImpinge** [comment]
No Problem @marty-suzuki. Thanks for your help.
