### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by IKepeRR** [marty-suzuki/URLEmbeddedView#17]
Good morning. I am using your library in my project (through pods), and it's really great. But with xcode 8, it's not building anymore :( Could u fix it pls, I need it very much

**Comment by IKepeRR** [comment]
Good morning. I am using your library in my project (through pods), and it's really great. But with xcode 8, it's not building anymore :( Could u fix it pls, I need it very much

**Comment by marty-suzuki** [comment]
Hi, @IKepeRR!
Thank you for your request!

I've released swift3 supported version.
But, [Kanna](https://github.com/tid-kijyun/Kanna) has not been supporting swift officially yet.

Please write Podfile following line.

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

# Swift3 supported Kanna has not released officially yet.
# You need to write following lines.
def swift3_overrides
pod 'Kanna', git: 'https://github.com/tid-kijyun/Kanna.git', branch: 'swift3.0'
end

target 'Your Project Name' do
swift3_overrides
pod 'URLEmbeddedView', :git => 'https://github.com/marty-suzuki/URLEmbeddedView.git', :tag => '0.6.0'
end
```

Thank you

**Comment by IKepeRR** [comment]
I did as u wrote, this is my podfile: http://joxi.ru/4AkZQnWIM3eLR2
But I got such errors: http://joxi.ru/VrwpnvkuK9dD7m
