### ISSUE TITLE
How can I make description multi-line?

### ISSUE THREAD

**Issue by scottfits** [marty-suzuki/URLEmbeddedView#19]
descriptionLabel is not an accessible property, but I want it to be 3 lines. What can I do?

**Comment by marty-suzuki** [comment]
Hi, @scottfits !

You can use multi-line following code.

```swift
embeddedView.textProvider[.Title].font = .boldSystemFontOfSize(12)
embeddedView.textProvider[.Title].numberOfLines = 1
embeddedView.textProvider[.Description].numberOfLines = 3
```

**Comment by scottfits** [comment]
perfect, thank you!

**Comment by heng5321** [comment]
@marty-suzuki  how about at objective C ?

**Comment by marty-suzuki** [comment]
this feature is not supported at objective-c
