### ISSUE TITLE
File not found for obj-c

### ISSUE THREAD

**Issue by guntidheerajkumar** [marty-suzuki/URLEmbeddedView#21]
Hi, As mentioned in the obj-c example, there is no file URLEmbeddedView/URLEmbeddedView-Swift.h. Please have a look in to it. I am trying to port that to C#.

**Comment by chirag225** [comment]
Same here URLEmbeddedView/URLEmbeddedView-Swift.h.  not found Please help

**Comment by marty-suzuki** [comment]
@guntidheerajkumar Sorry for late replying.
@chirag225 Hi!

Please install URLEmbeddedView via CocoaPods.
URLEmbeddedView-Swift.h dose not generate until you build project first time.
Thank you.

**Comment by chirag225** [comment]
I Added URLEmbeddedView  via CocoaPods and build project but not finding URLEmbeddedView-Swift.h . Where should i find this file

**Comment by marty-suzuki** [comment]
URLEmbeddedView-Swift.h is automatically generated by Xcode when project builds.
Therefore, it dose not exist if project building fails.

**Comment by guntidheerajkumar** [comment]
Thank you so much.

**Comment by marty-suzuki** [comment]
@chirag225 @guntidheerajkumar 
I've fix some issue.
Please write Podfile like this and try it!

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'Your Project Name' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Your Project Name
  pod 'URLEmbeddedView'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.0"
    end
  end
end
```

**Comment by chirag225** [comment]
I am getting Swift Compiler Error(147 Error) from CryptoSwift files

**Comment by marty-suzuki** [comment]
@chirag225 
What swift version do you use in your project? objc only?

**Comment by chirag225** [comment]
i use only Objective c and xcode 8.2.1 , I already use some  swift file using pods

**Comment by marty-suzuki** [comment]
What swift version do other swift frameworks in you project?
If those use swift2.3, you have to use URLEmbededView 0.5.0

**Comment by chirag225** [comment]
i am using all swift3.0 file

**Comment by Chirag89-JackSparrow** [comment]
Hello @marty-suzuki 
![screen shot 2018-08-11 at 3 37 22 pm](https://user-images.githubusercontent.com/42293779/43990698-a8fa1296-9d7c-11e8-8882-3923c9d3e6ec.png)
![screen shot 2018-08-11 at 3 38 23 pm](https://user-images.githubusercontent.com/42293779/43990699-a92b695e-9d7c-11e8-87e4-abac1b90b533.png)

I have project in Objective c and I facing same problem. 
I try your suggestion as follows but not work.

````
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ProjectName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectName
   
    pod 'URLEmbeddedView', '~> 0.16'

#    pod 'PhotoEditorSDK'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
````

Give me 28 Errors from your project.
