### ISSUE TITLE
can not fetch image with

### ISSUE THREAD

**Issue by ahmedAlmasri** [marty-suzuki/URLEmbeddedView#25]
Load Url return can not fetch image with 

ex: http://google.com

ex: https://www.sasapost.com/opinion/the-history-of-the-city-of-damascus

**Comment by marty-suzuki** [comment]
HI, @ahmedAlmasri 
Thank you for issue.

URLEmbededView conforms to The Open Graph protocol.
In the http://google.com case, that web site has `og:image` tag, but does not has `content` tag.

In the https://www.sasapost.com/opinion/the-history-of-the-city-of-damascus case, that web site has `og:image` and content` tag, but contains unreadable characters in content.
