### ISSUE TITLE
CryptoSwift is not needed and adds to compile time

### ISSUE THREAD

**Issue by beylerian** [marty-suzuki/URLEmbeddedView#26]
CryptoSwift is only used to call an md5 method, this is an inefficient use of the library.

**Comment by marty-suzuki** [comment]
I will examine the handling of that.

**Comment by beylerian** [comment]
thanks, a quick fix for it would be to include the MD5 method alone or another way to shorten the URLs

**Comment by marty-suzuki** [comment]
I've removed CryptoSwift!
Please check 0.8.1😄

**Comment by beylerian** [comment]
@marty-suzuki 
awesome thanks!
