### ISSUE TITLE
Does not work with Swift 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)

### ISSUE THREAD

**Issue by haansplosion** [marty-suzuki/URLEmbeddedView#27]
Produces hundreds of errors when installed via Cocoapods. Can be reduced down to 5 in "misterfusion" by converting all to latest syntax dialog, all of which are "Cannot invoke 'filter' with an argument list of type, etc"

**Comment by haansplosion** [comment]
Seems like an awesome library though 😄

**Comment by marty-suzuki** [comment]
I've released 0.8.1!
Please try it😄
