### ISSUE TITLE
Issue with links that do not contain "http://" or "https://"

### ISSUE THREAD

**Issue by richardfisher** [marty-suzuki/URLEmbeddedView#30]
I've come across an issue where if I try to load a URL that does not contain http:// or https:// that I get a positive response without an error from loadURL, however nothing appears inside the URLEmbeddedView. I got around this by appending the url I try to load with either http:// or https:// but it might be better if the URLEmbeddedView did this automatically or sent back some kind of error to say that the URL is not valid.

**Comment by marty-suzuki** [comment]
Hi, richardfisher

I think that url's web site does not confirm Open Graph Protocol.
If URLEmbeddedView receives no response, it would be shown a following card style.

![](https://raw.githubusercontent.com/marty-suzuki/URLEmbeddedView/master/SampleImages/sample02.png)

**Comment by richardfisher** [comment]
Hey marty-suzuki

Thanks for the response! I thought this might be the case with the URL I was trying originally but then I just tried google and still got the same result of an empty card:

![img_5440](https://cloud.githubusercontent.com/assets/673887/25473881/72f491da-2b31-11e7-80c0-10c48e7be286.PNG)
