### ISSUE TITLE
This library getting lot of errors in latest swift version in iOS

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [marty-suzuki/URLEmbeddedView#31]
I installed this library through pods, its installed successfully, but, unfortunately getting more errors which is unable to run app.

Please fix this.

**Comment by marty-suzuki** [comment]
I built URLEmbeddedView sample in Xcode 8.3.2, and it works fine.

**Comment by AnilkumarRabhasa** [comment]
Can you tell me how to install manually?

**Comment by marty-suzuki** [comment]
Manually installation is not recommended now.
