### ISSUE TITLE
No fetchOGData in Objective C

### ISSUE THREAD

**Issue by sohil12** [marty-suzuki/URLEmbeddedView#33]
How do I call fetchOGData in Objective C. Can you add a sample code for that. I need to fetch URL, siteName, pageTitle, pageDescription.

**Comment by inPhilly** [comment]
@sohil12 did you ever get this to work? stuck at exactly the same place : (

**Comment by marty-suzuki** [comment]
Please try to reference this objective-c based project.
[URLEmbeddedViewSampleObjc.zip](https://github.com/marty-suzuki/URLEmbeddedView/files/1393028/URLEmbeddedViewSampleObjc.zip)
