### ISSUE TITLE
Cannot force unwrap value of non-optional type 'NSManagedObjectModel'

### ISSUE THREAD

**Issue by raytso** [marty-suzuki/URLEmbeddedView#34]
Pods/URLEmbeddedView/URLEmbeddedView/OGDataCacheManager.swift:27:58: Cannot force unwrap value of non-optional type 'NSManagedObjectModel'

**Comment by raytso** [comment]
happens on Swift 3.2, Xcode 9 beta 5

**Comment by marty-suzuki** [comment]
Hi @raytso 
I've fixed with Xcode9 beta5.
Please try [this](https://github.com/marty-suzuki/URLEmbeddedView/tree/xcode9-beta5-build).
