### ISSUE TITLE
Doesn't work with Wikipedia links

### ISSUE THREAD

**Issue by trusk89** [marty-suzuki/URLEmbeddedView#38]
For instance, https://en.wikipedia.org/wiki/Carl_Garner_Federal_Lands_Cleanup_Day returns a view with just this URL in it.

**Comment by marty-suzuki** [comment]
This page is not confirm Open Graph Protocol.
Please check it with this.
http://opengraphcheck.com/result.php?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FCarl_Garner_Federal_Lands_Cleanup_Day#.WdncyRO0MUE
