### ISSUE TITLE
Cannot fetch image 

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [marty-suzuki/URLEmbeddedView#39]
Load Url return can not fetch image with

url : https://www.youtube.com/watch?v=IGyvbGHxUdg 

but when i check in this [website](http://opengraphcheck.com/result.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DIGyvbGHxUdg#.Wcxo7hOCzOQ). There is og:image tag. Please help me. thanks you. 

<img width="953" alt="screen shot 2017-09-28 at 3 03 32 pm" src="https://user-images.githubusercontent.com/8436265/30953376-39dc6ba6-a45e-11e7-8136-10c1fed14c15.png">

**Comment by BorjaCloobing** [comment]
I am facing same issue, any idea?

**Comment by marty-suzuki** [comment]
I'll investigate it.

**Comment by sarathdev** [comment]
For youtube links, I'm also not able to fetch the thumbnail image, any help

**Comment by marty-suzuki** [comment]
Youtube html does not have "og:xxx" property.
I need to use this link.
https://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DIGyvbGHxUdg

**Comment by AyeChanPyaeSone** [comment]
thanks you so much.

**Comment by marty-suzuki** [comment]
@AyeChanPyaeSone @sarathdev @BorjaCloobing 
I've released 0.10.2!
This is fixed version about youtube embeded info.
Please check it😀

**Comment by sarathdev** [comment]
@marty-suzuki Thanks, Marty. Your fix works for me on iPhone 5. But not working in iPhone 6s plus and iPad Air
