### ISSUE TITLE
Related to issue number #39

### ISSUE THREAD

**Issue by sarathdev** [marty-suzuki/URLEmbeddedView#44]
Hi, Suzuki Sorry to bother you again, How can I update to the specific version of the pod you specified in that bug number #39.
I tried updating to the latest version (0.12.0).
 But it won't help for me because I'm using 8.3.3 and the pod is upgraded for Swift 4

**Comment by sarathdev** [comment]
Sorry now I'm able to update the pod using 
pod **"URLEmbeddedView", '0.10.2'** command 
But still loading the Youtube thumbnails is not working for me with the updated repository

**Comment by marty-suzuki** [comment]
Could you paste that youtube link?

**Comment by sarathdev** [comment]
@marty-suzuki  Hi Sorry for the late reply. 
```
 let extractedUrl = sosReplyComment.comment.extractURLs()
            for url:URL in extractedUrl{
                for view in cell.urlPreviewViewOutlet.subviews {
                    if view is URLEmbeddedView{
                        view.removeFromSuperview()
                    }
                }
                
                let embeddedView:URLEmbeddedView = URLEmbeddedView()
                embeddedView.loadURL(url.absoluteString)
                embeddedView.borderColor = UIColor.clear
                embeddedView.cornerRaidus = 0
                embeddedView.frame = CGRect(x: 0, y:0, width: Int(cell.frame.width-20), height: 60)
                embeddedView.didTapHandler = { [weak self] embeddedView, URL in
                    guard let URL = URL else { return }
                    self?.present(SFSafariViewController(url: URL), animated: true, completion: nil)
                }
                
                cell.urlPreviewViewOutlet.addSubview(embeddedView)                
                break
            }
```
This is how I'm using your `URLEmbeddedView` to show hyperlink with a thumbnail in my `UITableviewCells`. But it is working perfectly sometime in my iPhone 5 but not in iPads and iPhone 6s plus. Most probably I might be doing something wrong in code

**Comment by marty-suzuki** [comment]
Would you try to add `embeddedView.cancelLoad()` before removeFromSuperview?

**Comment by sarathdev** [comment]
```
  let extractedUrl = sosReplyComment.comment.extractURLs()
            for url:URL in extractedUrl{
                for view in cell.urlPreviewViewOutlet.subviews {
                    if view is URLEmbeddedView{
                        view.removeFromSuperview()
                    }
                }
                
                let embeddedView:URLEmbeddedView = URLEmbeddedView()
                embeddedView.cancelLoad()
                embeddedView.loadURL(url.absoluteString)
                embeddedView.borderColor = UIColor.clear
                embeddedView.cornerRaidus = 0
                embeddedView.frame = CGRect(x: 0, y:0, width: Int(cell.frame.width-20), height: 60)
                embeddedView.didTapHandler = { [weak self] embeddedView, URL in
                    guard let URL = URL else { return }
                    self?.present(SFSafariViewController(url: URL), animated: true, completion: nil)
                }
                
                cell.urlPreviewViewOutlet.addSubview(embeddedView)
                cell.urlViewHeightConstarint.constant = 61
                
                break
            }
```
Added and tried but no help with it. but it was sometimes working in iPhone 5 not in other devices

**Comment by marty-suzuki** [comment]
that is wrong addtion.
i mean like this.

```swift
for view in cell.urlPreviewViewOutlet.subviews {
    if let embeddedView = view as? URLEmbeddedView {
        embeddedView.cancelLoad()
        embeddedView.removeFromSuperview()
    }
}
```

**Comment by sarathdev** [comment]
Just now i tried that as well but not working :( 

          ```
  let extractedUrl = sosReplyComment.comment.extractURLs()
            let embeddedView:URLEmbeddedView = URLEmbeddedView()

            for url:URL in extractedUrl{
                for view in cell.urlPreviewViewOutlet.subviews {
                    if view is URLEmbeddedView{
                        embeddedView.cancelLoad()
                        view.removeFromSuperview()
                    }
                }

```
The code change is pasted above

**Comment by marty-suzuki** [comment]
embeddedView and view is not same instance in the code posted above, therefore that code is wrong.
Could you **paste** URLs that is not loaded?
Or could you check open graph data with this link.
https://www.youtube.com/oembed?url=xxx

**Comment by sarathdev** [comment]
Not single URL. All youtube URL's are not loading its thumbnails. 
Tried with the sample that mentioned in the comment also

**Comment by marty-suzuki** [comment]
Sorry, i can not investigate without information such as url sample.

**Comment by sarathdev** [comment]
@marty-suzuki thanks for your valuable time and replies. But the problem I'm facing is I have tried many of youtube links and no youtube links returned thumbnails for me. But these same returned once in iPhone 5 as I already said before I will attach you some of the screenshots and URLs for your reference

https://www.youtube.com/watch?v=C0DPdy98e4c

https://www.youtube.com/watch?v=PCwL3-hkKrg
![screen shot 2017-10-18 at 11 02 36 am](https://user-images.githubusercontent.com/11920131/31702439-a6048db8-b3f4-11e7-97b2-be298784bdec.png)

![screen shot 2017-10-18 at 11 02 36 am](https://user-images.githubusercontent.com/11920131/31702358-31d1800e-b3f4-11e7-98a1-f28b2b726a85.png)
![screen shot 2017-10-16 at 12 38 23 pm](https://user-images.githubusercontent.com/11920131/31702366-3a43e16e-b3f4-11e7-87d2-c913e21c1141.png)

**Comment by marty-suzuki** [comment]
I've recognized what is wrong.
URL host of your screenshots are `m.youtube.com`.
You need to replace `m.youtube.com` to `www.youtube.com`.
So your code should be like this.

```swift
let extractedUrls = sosReplyComment.comment.extractURLs()
for extractedUrl in extractedUrls {
    let url: URL
    if extractedUrl.host?.contains("m.youtube.com") == true {
        var components = URLComponents(string: extractedUrl.absoluteString)
        components?.host = "www.youtube.com"
        if let _url = components?.url {
            url = _url
        } else {
            url = extractedUrl
        }
    } else {
        url = extractedUrl
    }

    for view in cell.urlPreviewViewOutlet.subviews {
        if let ev = view as? URLEmbeddedView {
            ev.cancelLoad()
            ev.removeFromSuperview()
        }
    }
                
    let embeddedView:URLEmbeddedView = URLEmbeddedView()
    embeddedView.loadURL(url.absoluteString)
    embeddedView.borderColor = .clear
    embeddedView.cornerRaidus = 0
    embeddedView.frame = CGRect(x: 0, y:0, width: cell.frame.width - 20, height: 60)
    embeddedView.didTapHandler = { [weak self] _, url in
        guard let url = url else { return }
        self?.present(SFSafariViewController(url: url), animated: true, completion: nil)
    }
                
    cell.urlPreviewViewOutlet.addSubview(embeddedView)
    cell.urlViewHeightConstarint.constant = 61
                
    break
}
```

**Comment by sarathdev** [comment]
Thank you very much @marty-suzuki. I will update the code and let you know if its going somewhere wrong

**Comment by sarathdev** [comment]
@marty-suzuki Thank you very much brother, for your library and support now its working awesome :) 💯
