### ISSUE TITLE
Crash using Carthage install in Objective-C Project

### ISSUE THREAD

**Issue by inPhilly** [marty-suzuki/URLEmbeddedView#46]
When installed with Carthage in an Objective-C project, this crashes when the list cells are shown:

`let fetchedList = (try? managedObjectContext.fetch(fetchRequest))`

in the 

`fetchOGData`

method.

**Comment by marty-suzuki** [comment]
It is fixed greater than  0.12.0
Please use latest version

**Comment by inPhilly** [comment]
Carthage pulls 0.12.0. I am new to Carthage so I haven't found a way to specify the version. I just found this info: "Carthage does not support prerelease versions." Is this a prerelease version? Thanks.

**Comment by inPhilly** [comment]
Can you possibly push the next version after 0.12.0 to Carthage?

**Comment by inPhilly** [comment]
I am using 0.12.0 and this is where I have been getting this error.

**Comment by marty-suzuki** [comment]
This is Objective-C sample project's screen capture.
It works fine with Carthage update.

![objc-sc](https://user-images.githubusercontent.com/2082134/31647394-da4bc134-b342-11e7-95be-c1f881c4e02b.png)

If you can not launch app, please try to add Dummy.swift(this is empty swift file) and bridging-header.h(this is created by xcode).

**Comment by inPhilly** [comment]
I'm not trying to be difficult, but I do think your sample project is a different case. In your sample project, you are importing Objective-C into a Swift Project. In my project, I am importing Swift into an Objective-C project.

**Comment by inPhilly** [comment]
Bridging-header.h is what is used in a Swift project to import objective-c code. So unfortunately, that makes the sample you have above a Swift project. I am so sorry to bother you, I am just so excited about this code and really want to get it to work in my objective-c app. I wish I knew Swift, but this is an old app and I don't know Swift yet.

**Comment by marty-suzuki** [comment]
I think your understanding is wrong.
[This comment](https://github.com/marty-suzuki/URLEmbeddedView/issues/46#issuecomment-337117916) is new Objective-C base project.
This is no [uploaded example](https://github.com/marty-suzuki/URLEmbeddedView/tree/master/Example).
First of all, libswiftCore.dylib is needed to use Swift.
Objective-C base project dose not contain libswiftCore.dylib, therefore you need to add Dummy.swift(this is empty swift file) to your Objective-C project.

In addition, I've uploaded [URLEmbeddedViewSampleObjc.zip](https://github.com/marty-suzuki/URLEmbeddedView/files/1393021/URLEmbeddedViewSampleObjc.zip) which is Objective-C base URLEmbeddedVIew project.
To read this project, you will notice your wrong understanding.

**Comment by inPhilly** [comment]
Thanks for the sample project. I can't get it to run even though it does build. It crashes each time with this error:
dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/home/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/URLEmbeddedView.framework/URLEmbeddedView
  Reason: image not found

**Comment by marty-suzuki** [comment]
What is your Carthage version?

**Comment by inPhilly** [comment]
0.26.2

**Comment by inPhilly** [comment]
Does that library require cocoapods?

**Comment by inPhilly** [comment]
dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/home/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/URLEmbeddedView.framework/URLEmbeddedView
  Reason: image not found
(lldb)

**Comment by inPhilly** [comment]
dyld: Library not loaded: 

> @rpath/libswiftSwiftOnoneSupport.dylib

  Referenced from: /Users/home/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/URLEmbeddedView.framework/URLEmbeddedView
  Reason: image not found
(lldb)

**Comment by marty-suzuki** [comment]
That sample is work perfectly in my environment with Carthage 0.26.2

**Comment by inPhilly** [comment]
The libswiftSwiftOnoneSupport library seems to be the issue. I ran your code as is and I get the above error. Crazy!

**Comment by inPhilly** [comment]
I am using Version 9.0.1 (9A1004) of XCode by the way

**Comment by inPhilly** [comment]
And running this in iPhone X Simulator

**Comment by marty-suzuki** [comment]
Please try `carthage update`.

**Comment by inPhilly** [comment]
Yes, I had done that already. Still get the libswiftSwiftOnoneSupport error. Ugh.

**Comment by marty-suzuki** [comment]
Dose it work your environment?
[URLEmbeddedViewSampleObjc2.zip](https://github.com/marty-suzuki/URLEmbeddedView/files/1395595/URLEmbeddedViewSampleObjc2.zip)

**Comment by inPhilly** [comment]
So odd. Once I deleted the bad (missing) framework at the top it does build. But the same error when it runs:

dyld: Library not loaded: @rpath / libswiftCoreData . dylib
  Referenced from: /Users/home/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/URLEmbeddedView.framework/URLEmbeddedView
  Reason: image not found

**Comment by inPhilly** [comment]
Even when I replace that 'bad' library at the top by dragging the Carthage/Build/iOS library there, I still get the same error

**Comment by marty-suzuki** [comment]
I've updated xcode 9.0.1 and try to run that sample. It works fine.

**Comment by inPhilly** [comment]
I think this is the issue I am having:
https://github.com/Carthage/Carthage/issues/1394#issuecomment-233958908

**Comment by marty-suzuki** [comment]
Do you try to make "Always Embed Swift Standard library" to "true"?
<img width="862" alt="2017-10-19 2 30 03" src="https://user-images.githubusercontent.com/2082134/31733065-73fa9c28-b475-11e7-9286-38d78711f314.png">

**Comment by inPhilly** [comment]
I can't get the swift libraries to show up in my project

**Comment by inPhilly** [comment]
Yes, I have tried that and it doesn't help unfortunately : (

**Comment by inPhilly** [comment]
I feel like maybe I need to add it as an embedded library

**Comment by marty-suzuki** [comment]
Embedded library sample project is already in [this comment].
That is not use carthage, but It references URLEmbeddedView.xcproject.

**Comment by inPhilly** [comment]
okay, I did get it to embed, but this is the error I am getting in my project which I actually think is causing the problem
/Carthage/Checkouts/URLEmbeddedView/Resources/URLEmbeddedViewOGData.xcdatamodeld: Missing current version declaration

**Comment by inPhilly** [comment]
Can you tell me the steps you took to embed it in the sample project?

**Comment by inPhilly** [comment]
Now I'm back to the original error - a crash on

`let fetchedList = (try? managedObjectContext.fetch(fetchRequest))`

in the

`fetchOGData`

method. Banging my head on the wall.

**Comment by inPhilly** [comment]
OK - getting there. It's a multithreading violation. I have something turned on in my code which crashes on multithreading violations. Don't know how to fix it though. Tried running in the background but I get the feeling the violation may *possibly* be in the project itself - is this possible?

**Comment by inPhilly** [comment]
CoreData`+[NSManagedObjectContext __Multithreading_Violation_AllThatIsLeftToUsIsHonor__]:

**Comment by inPhilly** [comment]
This is what I have turned on:
https://oleb.net/blog/2014/06/core-data-concurrency-debugging/

**Comment by inPhilly** [comment]
Yup! That was it! When I turn off that setting it works. When I turn on that setting in the sample project it crashes. So the issue is a multithreading violation in URLEmbeddedView.

**Comment by inPhilly** [comment]
So I have continued to test and ultimately I do think your Carthage installation is fine. "Always Embed Swift Standard Libraries" does *not* have to be set to YES (it is no in your sample project and I find I do not need it to be set to YES either). The error is a multithreading violation in URLEmbeddedView. Mystery solved - although the problem still remains! I don't know Swift (obviously) or I would try to help you debug. I suspect maybe a missing `performBlock`? https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreData/Concurrency.html

**Comment by marty-suzuki** [comment]
Thank you for your investigation!
Let me make sure one thing, this code is crashed in your project?

```objective-c
NSURL *url = ...
[[OGDataProvider sharedInstance] fetchOGDataWithUrlString: url.absoluteString, completion: ^(OGData *ogData, NSError *error) {
    NSLog(@"ogData = %@", ogData);
    NSLog(@"any error = %@", error);        
}];
```

This code can get OGData directly.

**Comment by inPhilly** [comment]
Yes - that is actually what I am using. That crashes in the project. Were you able to reproduce by changing that setting in the sample project?

**Comment by inPhilly** [comment]
And thank you for your patience in working through things with me!

**Comment by inPhilly** [comment]
Do you think you will have any time to work on a fix for this. I understand time is limited. Again, I wish I knew Swift so I could help!

**Comment by marty-suzuki** [comment]
I've released 0.13.0!
Please try it😀

**Comment by inPhilly** [comment]
Yay! Latest version in Carthage is 0.12.0 though, so I can't update until it has been changed to 0.13.0 unfortunately...

**Comment by inPhilly** [comment]
I will look forward to updating. I also had a couple of other thoughts. 1) Have you ever thought of searching for the Twitter: share tag as well as the og: ? 2) Have you considered creating a non-core-data cache (more of a short term cache)? When I shut down my project with this code in it in the simulator, it also crashes upon next startup (which I think might be related to the issue you are solving). But I use Core Data in my project and I would rather not utilize it in a library. Is there more of a short-term way to cache the links without using Core Data? Thanks again for this great library and I look forward to trying the fix when Carthage gets updated.

**Comment by marty-suzuki** [comment]
I could update via Cartahge.
<img width="829" alt="2017-10-22 17 50 42" src="https://user-images.githubusercontent.com/2082134/31860205-ac5255be-b751-11e7-9f49-40b58061306c.png">.
URLEmbeddedView creates another SQLite file (CoreData uses SQLite inside) that does not affect your project's SQLite file.
So I think another caching system is not needed.

**Comment by inPhilly** [comment]
Hi Marty! I couldn't come back to this because I was busy, but I am back now! I am nervous about adding anything core data because it is SO touchy (as we have seen) and just prone-to error. If I install the repository in my app, is there any way to do it without a core data database being installed in the app?
