### ISSUE TITLE
@objc  removed from fetchOGData??

### ISSUE THREAD

**Issue by inPhilly** [marty-suzuki/URLEmbeddedView#50]
Hi Marty. I think you may have inadvertently removed @objc  from the fetchOGData method??

**Comment by inPhilly** [comment]
I can't even install this in Objective-C project anymore. I'm about to give up. I think your Carthage instructions might leave out a lot of steps in the embedded process. I'm just really confused because I thought I had this working with Carthage and Objective-C, besides the crash, and tonight I spent the entire night trying to get this back in and I simply couldn't do it.

**Comment by marty-suzuki** [comment]
Hi, I've fixed it!
Please use 0.14.0!

You can use fetch method like this.
```objective-c
[[OGDataProvider sharedInstance] fetchOGDataWithUrlString:self.textView.text
                                        completion:^(OpenGraphData *data, NSError *error) {
  NSLog(@"OpenGraphData = %@", data);
}];
```
