### ISSUE TITLE
Install without Core Data?

### ISSUE THREAD

**Issue by inPhilly** [marty-suzuki/URLEmbeddedView#52]
Hi Marty! I understand that there is no way to cache without Core Data, and I can't include another Core Data database in my app at this time, so I am planning on using 'fetch the info' only. Is there any way to install URLEmbeddedView without the repository creating a Core Data store at all? Like 'URLEmbeddedView Light'? : )

**Comment by marty-suzuki** [comment]
Hi, there is no way to install URLEmbeddedView without CoreData.
Although the deadline is not fixed, perhaps it may be implemented in the near future.

**Comment by inPhilly** [comment]
I just really need to be able to fetch the data for an individual url. I can try to extract the relevant files but the only reason I ask is that I don't know Swift. I will see if I can find a way to do it. I really like this repository.
