### ISSUE TITLE
Carthage Installation in Objective-C Project - Steps

### ISSUE THREAD

**Issue by inPhilly** [marty-suzuki/URLEmbeddedView#53]
Since the last time I installed the repository and removed it, I cannot get it to install again. I have the Summy.swift file created. Do you happen to have all of the steps needed to embed the project in an Objective-C app, hopefully via Carthage, handy? I am not sure how I ended up getting it installed last time, but I have been trying and cannot get it in this time without getting this error on 'Run':

yld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/home/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/URLEmbeddedView.framework/URLEmbeddedView
  Reason: image not found
(lldb) 

I know I'm an idiot for not being able to figure this out, but if you have the steps handy that would be helpful. Thanks. : )

**Comment by inPhilly** [comment]
Also, I saw in your Objective-C page example, you use:
#import <URLEmbeddedView/URLEmbeddedView-Swift.h>

When, in an Objective-C project, we typically would use
#import <URLEmbeddedView/URLEmbeddedView.h>

**Comment by inPhilly** [comment]
I *think* I got it. Here are my steps:
1. Update Carthage build Carthage ('carthage update URLEmbeddedView' in Terminal)
2. drag URLEmbeddedView.framework from Carthage/Build/iOS into project and make sure appropriate Target Membership(s) are checked
3. Target/General tab - hit + button in Embedded Binaries section and select URLEmbeddedView.framework to add
4. Target/Build Phases tab - hit + button in Run Script section for 
/usr/local/bin/carthage copy-frameworks
and add
$(SRCROOT)/Carthage/Build/iOS/URLEmbeddedView.framework
5. Delete Derived Data!
6. use #import <URLEmbeddedView/URLEmbeddedView.h> where needed
7. Build and run

**Comment by marty-suzuki** [comment]
Hi, I have not written these steps because there are just common sense for carthage users.
Please refer this document ([Adding frameworks to an application](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application)).
