### ISSUE TITLE
Sample Project Build Error related to recent fix

### ISSUE THREAD

**Issue by inPhilly** [marty-suzuki/URLEmbeddedView#54]
"Method 'fetchOGData(urlString:completion:)' with Objective-C selector 'fetchOGDataWithUrlString:completion:' conflicts with method 'fetchOGDataWithUrlString(_:completion:)' with the same Objective-C selector"

**Comment by adeelnoor** [comment]
There was a same problem with my project, just renaming this method solved my issue.
