### ISSUE TITLE
Not getting website image for specific URL

### ISSUE THREAD

**Issue by parthpatel1105** [marty-suzuki/URLEmbeddedView#60]
I am using this framework for objective C and it's working fine here. But sometimes I am not getting image of particular website and not getting website title properly. Here I am providing you one website URL as sample in which I am facing both issue for image and title.

[https://www.cnbc.com/2018/05/02/effectiveness-of-tesla-autopilot-was-not-assessed-nhtsa.html](url)

In above URL I am not getting image and title with uneven characters like `&#039;`

[https://feedproxy.google.com/~r/entrepreneur/latest/~3/EQ33cmQbh3Q/312846](url)

For this URL I am getting null website title. I am using latest code for URLEmbeddedView.

@marty-suzuki Please do needful help for this issue. 

Thank you.

**Comment by marty-suzuki** [comment]
Hi, @parthpatel1105 
Sorry for replying late.

Those issues are fixed latest version.

| https://www.cnbc.com | https://feedproxy.google.com |
| :-: | :-: |
| <img width="598" alt="2018-07-08 1 43 38" src="https://user-images.githubusercontent.com/2082134/42413247-6e0d0fc0-8257-11e8-8f04-12a3f02d5d7a.png"> | <img width="598" alt="2018-07-08 1 43 57" src="https://user-images.githubusercontent.com/2082134/42413248-701144a8-8257-11e8-870a-0ec668135645.png"> |

**Comment by parthpatel1105** [comment]
Great work!!!

Thank you so much.
