### ISSUE TITLE
Adding @objc to each OpenGraphData property

### ISSUE THREAD

**Issue by CalvinTp** [marty-suzuki/URLEmbeddedView#62]
Hi,
To compile Objective C under Swift 4, each property needs to add @Objc to allow Objective c to access them. Can you help to add the codes below? 

@objc public class OpenGraphData: NSObject {
    @objc public let createdAt: Date
    @objc public let imageUrl: URL?
    @objc public let pageDescription: String?
    @objc public let pageTitle: String?
    @objc public let pageType: String?
    @objc public let siteName: String?
    @objc public let sourceUrl: URL?
    @objc public let updatedAt: Date
    @objc public let url: URL?

Thanks for sharing the codes and appreciate it :) 

Thanks,
Calvin

**Comment by marty-suzuki** [comment]
Hi, @CalvinTp 

Those have already added at 0.15.1
Please check [this line](https://github.com/marty-suzuki/URLEmbeddedView/blob/0.15.1/URLEmbeddedView/Core/OpenGraph.swift#L111).

Thanks
