### ISSUE TITLE
Value of type '[(_, CGFloat?)]' has no member 'compactMap'

### ISSUE THREAD

**Issue by Ilesh** [marty-suzuki/URLEmbeddedView#64]
func addConstraints(with view: UIView,
                        size: Size,
                        relatedBy relation: NSLayoutRelation = .equal,
                        multiplier: CGFloat = 1) {
        view.translatesAutoresizingMaskIntoConstraints = false
        **addConstraints([**
                (.width, size.width),
                (.height, size.height)
            ]
            .compactMap { (value: (NSLayoutAttribute, CGFloat?)) in
                value.1.map {
                    .init(item: view,
                          attribute: value.0,
                          relatedBy: relation,
                          toItem: nil,
                          attribute: .notAnAttribute,
                          multiplier: multiplier,
                          constant: $0)
                }
            }
        )
    }

**Comment by salvimayur89** [comment]
Any Solution????????

**Comment by TaoufikBouabid** [comment]
compactMap(_:) was introduced in Swift 4.1; in Swift 4.0.x it's flatMap(_:)

**Comment by marty-suzuki** [comment]
Hi @Ilesh 
I've support both of `compactMap(:)` and `flatMap(:)`.
Please try 0.15.2
