### ISSUE TITLE
Value of type 'Any' has no member '1'

### ISSUE THREAD

**Issue by swiftty** [marty-suzuki/URLEmbeddedView#65]
In two places, I get this error.Both are in the AutoLayout.swift file. 

      `func addConstraints(with view: UIView,
                        size: Size,
                        relatedBy relation: NSLayoutRelation = .equal,
                        multiplier: CGFloat = 1) {
        view.translatesAutoresizingMaskIntoConstraints = false
        addConstraints([
                (.width, size.width),
                (.height, size.height)
            ]
            .flatMap { value in
                value.1.map {
                    .init(item: view,
                          attribute: value.0,
                          relatedBy: relation,
                          toItem: nil,
                          attribute: .notAnAttribute,
                          multiplier: multiplier,
                          constant: $0)
                }
            }
        )
    }`

      `func addConstraints(with view: UIView, edges: Edges, multiplier: CGFloat = 1) {
        view.translatesAutoresizingMaskIntoConstraints = false
        addConstraints([
                (.top, edges.top),
                (.left, edges.left),
                (.right, edges.right),
                (.bottom, edges.bottom)
            ]
            .flatMap { value in
                value.1.map {
                    .init(item: view,
                          attribute: value.0,
                          relatedBy: .equal,
                          toItem: self,
                          attribute: value.0,
                          multiplier: multiplier,
                          constant: $0)
                }
            })
    }`

Along with a bunch of warnings: 

![screenshot 2018-06-21 at 2 17 07 pm](https://user-images.githubusercontent.com/13771527/41716057-ef209958-755d-11e8-82f1-2d97cf394d49.png)

**Comment by marty-suzuki** [comment]
Hi, @swiftty 
Please try 0.15.2
