### ISSUE TITLE
OG data is not fully parsed 

### ISSUE THREAD

**Issue by Luten** [marty-suzuki/URLEmbeddedView#70]
Tried with version `0.15.3` (we need ios8)
Here are the results of library for url `https://www.imdb.com/title/tt5095030/`:
```
createdAt = Wed Jul 18 13:25:53 2018
imageUrl = (null)
pageDescription = Directed by Peyton Reed.  With Paul Rudd, Evangeline Lilly, Michael Peña, Walton Goggins. As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.
pageTitle = (null)
pageType = (null)
siteName = (null)
sourceUrl = https://www.imdb.com/title/tt5095030/
updatedAt = Wed Jul 18 13:25:57 2018
url = http://www.imdb.com/title/tt5095030/
```
While there are not null tags (can be seen in source html, or by tools like https://opengraphcheck.com/result.php?url=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt5095030%2F#.W07dRdgzZTY)
```
og:url | http://www.imdb.com/title/tt5095030/
og:image | https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY1200_CR90,0,630,1200_AL_.jpg
og:type | video.movie
og:title | Ant-Man and the Wasp (2018)
og:site_name | IMDb
og:description | Directed by Peyton Reed. With Paul Rudd, Evangeline Lilly, Michael Peña, Walton Goggins. As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.
```

**Comment by Luten** [comment]
Same results with `0.16.1` version

**Comment by marty-suzuki** [comment]
@Luten 
I've fixed and support iOS8 again.
Please try 0.16.2

**Comment by Luten** [comment]
Thanks for fast reaction!
But this fix didn't help =(
`Using URLEmbeddedView (0.16.2)`
```
imageUrl = (null)
pageDescription = Directed by Peyton Reed.  With Paul Rudd, Evangeline Lilly, Michael Peña, Walton Goggins. As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.
pageTitle = (null)
pageType = (null)
siteName = (null)
sourceUrl = https://www.imdb.com/title/tt5095030/
url = http://www.imdb.com/title/tt5095030/
```

**Comment by marty-suzuki** [comment]
I've tries https://www.imdb.com/title/tt5095030/  with `0.16.2`.
It works fine like below image.
<img width="598" alt="2018-07-18 20 06 10" src="https://user-images.githubusercontent.com/2082134/42877867-0b9b3d36-8ac6-11e8-83f0-2612725a0e5a.png">

**Comment by Luten** [comment]
That's strange..
It worked for https://www.imdb.com/title/tt4701182/, but still didn't work for https://www.imdb.com/title/tt5095030/
Looks like it is a cache issue, I'll clear it all and will get back here

**Comment by Luten** [comment]
Yeah, that did it.
Cleared cache - and now it all works fine.
@marty-suzuki Huge thanks again for your time, efforts and very fast reaction!
