### ISSUE TITLE
Page description is not available

### ISSUE THREAD

**Issue by hamzahz** [marty-suzuki/URLEmbeddedView#72]
![screen shot 2018-08-21 at 5 18 02 pm](https://user-images.githubusercontent.com/17777173/44400877-40f75b80-a566-11e8-8880-151f1db6b820.png)

**Comment by hamzahz** [comment]
@marty-suzuki any updates here?

**Comment by marty-suzuki** [comment]
Hi, @hamzahz 
This is same issue as #70
It had fixed `0.16.2`

**Comment by marty-suzuki** [comment]
Hi, @hamzahz 

https://facebook.com has `og:site_name`, `og:url`, `og:image` and `og:local`.
Therefore, pageTitle, pageType and pageDescription are nil.
It's in the specifications.

<img width="952" alt="screen_shot" src="https://user-images.githubusercontent.com/2082134/48272524-2906e800-e482-11e8-82a3-b7eabcb8e777.png">
