### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by Luten** [marty-suzuki/URLEmbeddedView#82]
Hello, would you please update project for Swift 5 support

**Comment by Luten** [comment]
@marty-suzuki Is this project still supported?

**Comment by maulik3107** [comment]
Not working in swift 5
Please help

**Comment by marty-suzuki** [comment]
Hi, @maulik3107 @Luten .
I've supported Swift5 since 0.18.0 #83

**Comment by maulik3107** [comment]
Hello! Thanks its now working, but in only pass fb.com then it's not set image & url
